### ISSUE TITLE
Generate new password on every click

### ISSUE THREAD

**Issue by yakuter** [passwall/passwall-desktop#11]
**Describe the bug**
We have password generate icon on password fields. However it works just for once on first click. User should be able to change this generated password. So we should make this icon generate new password on every click.

<img width="404" alt="Screen Shot 2020-07-06 at 11 50 31" src="https://user-images.githubusercontent.com/3696314/86575025-4e156c00-bf7f-11ea-9cc8-edee17e106dc.png">

Does anyone wants to work on this?

**Comment by umutbozdag** [comment]
Can i take this?

**Comment by yakuter** [comment]
Great thank you.
