### ISSUE TITLE
User's name's first letters should be added

### ISSUE THREAD

**Issue by yakuter** [passwall/passwall-desktop#13]
**Is your feature request related to a problem? Please describe.**
In the design of passwall desktop app, we have user's first and last name's first letters next to user name. Can someone add this nice thing?

<img width="260" alt="Screen Shot 2020-07-06 at 15 52 53" src="https://user-images.githubusercontent.com/3696314/86595366-4b2b7300-bfa1-11ea-9b78-9031e6d47cf4.png">

**Comment by umutbozdag** [comment]
Can i take this one too?

**Comment by yakuter** [comment]
Of course, thank you :)
