### ISSUE TITLE
How can we get and store icons of websites?

### ISSUE THREAD

**Issue by yakuter** [passwall/passwall-desktop#15]
**Is your feature request related to a problem? Please describe.**
As seen in the design, we fetch the icons of websites like twitter, facebook, gmail. How can we do this in code? May be fetching from somewhere wont be a problem but what about storing these icons?

<img width="479" alt="Screen Shot 2020-07-07 at 09 33 53" src="https://user-images.githubusercontent.com/3696314/86728311-03eec200-c035-11ea-8c73-504cf0e7803e.png">

**Comment by umutbozdag** [comment]
We can use something like [this](https://clearbit.com/logo) for getting logos. 

By storing, what do you mean exactly? storing in a json file?

**Comment by yakuter** [comment]
I mean do we need to store or not? I think we do not need to store icons for now. Maybe in the future we can think about offline usage and storage but not now.

Anyway Clearbit seems nice. @umutbozdag if you have time, can you handle this?

**Comment by umutbozdag** [comment]
Yeah i can handle this. What should we show to user when there is no logo?

**Comment by yakuter** [comment]
Great. just use an empty icon which I can change later. I will talk to designer and get an icon from him.
