### ISSUE TITLE
Parse CSV data to array

### ISSUE THREAD

**Issue by yakuter** [passwall/passwall-desktop#18]
**Is your feature request related to a problem? Please describe.**
Now import function is added ass seen in the picture. User should import csv files with this. 
<img width="533" alt="Screen Shot 2020-07-15 at 23 03 36" src="https://user-images.githubusercontent.com/3696314/87590503-8d665a00-c6ef-11ea-9bb4-ade42c6682c2.png">

I am going to encrypt and add values to database however I need someone to parse this csv content line by line as array. The import handle function is in **/src/renderer/App.vue** like this:
```js
  onImport() {
      dialog.showOpenDialog({ properties: ['openFile'] }, files => {
        if (files.length === 0) return

        try {
          const fileContent = fs.readFileSync(files[0]).toString()
          // TODO: Parse fileContent (CSV data) to array
          console.log(fileContent)
        } catch (error) {
          console.log(error)
        }
      })
    }
```

**Describe the solution you'd like**
Example CSV content is here
https://github.com/passwall/passwall-server/blob/master/example.csv

Can someone parse and give me the values of CSV lines as array and javascript variables?

Thank you.

**Comment by yakuter** [comment]
Hey @umutbozdag or @bufgix do you have time for this?

**Comment by umutbozdag** [comment]
Is something like this okay? @yakuter 

![example](https://user-images.githubusercontent.com/43722871/87851647-67190800-c903-11ea-9c5b-a58d6e39882f.png)

**Comment by yakuter** [comment]
> Is something like this okay? @yakuter
> 
> ![example](https://user-images.githubusercontent.com/43722871/87851647-67190800-c903-11ea-9c5b-a58d6e39882f.png)
> 
> Or this?
> 
> ![example2](https://user-images.githubusercontent.com/43722871/87851744-75b3ef00-c904-11ea-989a-452016dc6d25.png)

The second model (mapping style) is what I need. By the way the URL, Username and Password fields can be changed according to the first line (column names) of CSV file. So, can we create this map dynamically according to CSV file? If not the static model you show is OK.

**Comment by umutbozdag** [comment]
> > Is something like this okay? @yakuter
> > ![example](https://user-images.githubusercontent.com/43722871/87851647-67190800-c903-11ea-9c5b-a58d6e39882f.png)
> > Or this?
> > ![example2](https://user-images.githubusercontent.com/43722871/87851744-75b3ef00-c904-11ea-989a-452016dc6d25.png)
> 
> The second model (mapping style) is what I need. By the way the URL, Username and Password fields can be changed according to the first line (column names) of CSV file. So, can we create this map dynamically according to CSV file? If not the static model you show is OK.

Yeah actually i am creating fields by header (column) names dynamically @yakuter

**Comment by yakuter** [comment]
Great. Assigned you now @umutbozdag
