### ISSUE TITLE
Add loading state to form buttons

### ISSUE THREAD

**Issue by yakuter** [passwall/passwall-desktop#20]
**Is your feature request related to a problem? Please describe.**
Now we have a loading state for the first Login buton.
<img width="400" alt="Screen Shot 2020-07-28 at 00 17 35" src="https://user-images.githubusercontent.com/3696314/88593165-d3181080-d067-11ea-89fd-f9263219665f.png">

**Describe the solution you'd like**
We should copy the same loading state to all form buttons in project? I mean Save buttons in Create and Update forms for all categories.
<img width="386" alt="Screen Shot 2020-07-28 at 00 19 18" src="https://user-images.githubusercontent.com/3696314/88593299-0064be80-d068-11ea-9bba-e5f066e04c68.png">

Does anyone want to work on this?

**Comment by oguzhaninan** [comment]
Done 👍

**Comment by yakuter** [comment]
Thank you @oguzhaninan
