### ISSUE TITLE
Long URL problem

### ISSUE THREAD

**Issue by yakuter** [passwall/passwall-desktop#22]
**Describe the bug**
Long URL's are problematic as in the screenshot.
![Screen Shot 2020-08-05 at 11 42 40](https://user-images.githubusercontent.com/3696314/89393672-ce142a80-d713-11ea-86b9-7e781b371968.png)

**To Reproduce**
We should shorten long URL's with three dots (...)

**Comment by bufgix** [comment]
i can handle this
