### ISSUE TITLE
Add Cancel button to create/edit forms

### ISSUE THREAD

**Issue by yakuter** [passwall/passwall-desktop#24]
**Is your feature request related to a problem? Please describe.**
We only have Save button at forms. I don't know why we did this in the first place :) Can someone add a cancel button to forms as in the image?

<img width="396" alt="Screen Shot 2020-08-09 at 23 54 51" src="https://user-images.githubusercontent.com/3696314/89741659-bfbf6900-da9b-11ea-8b7f-bfb5252a7cb0.png">

<img width="627" alt="Screen Shot 2020-08-09 at 23 52 00" src="https://user-images.githubusercontent.com/3696314/89741643-97d00580-da9b-11ea-9a18-9d0404612e5b.png">

**Comment by oguzhaninan** [comment]
Done
