### ISSUE TITLE
Use first letter if company logo not found

### ISSUE THREAD

**Issue by yakuter** [passwall/passwall-desktop#25]
**Is your feature request related to a problem? Please describe.**
We use company logos related to logins. However if there is no company logo, we should use the first letter of title as in the image below.

<img width="501" alt="Screen Shot 2020-08-10 at 23 04 22" src="https://user-images.githubusercontent.com/3696314/89825941-0f666900-db5e-11ea-815c-b40bec57d21f.png">

Also we need to add company logo/first letter to the detail view on top right.
<img width="955" alt="Screen Shot 2020-08-11 at 00 26 54" src="https://user-images.githubusercontent.com/3696314/89833353-8f460080-db69-11ea-8ef2-295a947955e4.png">

@umutbozdag do you have time for this?

**Comment by umutbozdag** [comment]
Yes. I can take this

**Comment by umutbozdag** [comment]
I can't login into my account by using the `https://vault.passwall.io` baseURL and i don't want to setup local server because it was working as expected before. It gives an error like this: `code: 401
errors: null
message: "Email is not verified!"
status: "Error"`

How can i fix this? @yakuter

**Comment by yakuter** [comment]
I just checked, your email seems activated successfully. Do you still have problem with it? @umutbozdag
