### ISSUE TITLE
Scroll bar needed on detail (right sidebar)

### ISSUE THREAD

**Issue by yakuter** [passwall/passwall-desktop#3]
**Describe the bug**
On the detail column (right one) we need a scrollbar. Especially in servers and bank accounts categories.
<img width="460" alt="Screen Shot 2020-07-03 at 23 19 30" src="https://user-images.githubusercontent.com/3696314/86495955-f0690000-bd83-11ea-8310-3a21af1e17f1.png">

Does anyone want to work on this?

**Comment by bufgix** [comment]
I want to work on this

**Comment by yakuter** [comment]
Great. I assigned you now. Let's give it a try.

**Comment by yakuter** [comment]
Closed with #6

Thank you @bufgix
