### ISSUE TITLE
Add build for Linux and Windows

### ISSUE THREAD

**Issue by yakuter** [passwall/passwall-desktop#5]
**Is your feature request related to a problem? Please describe.**
It is easy to build Electron app for multi platform. Can someone add build scenarios for Windows and Linux?

**Comment by oguzhaninan** [comment]
I will add. 👍

**Comment by yakuter** [comment]
@oguzhaninan I see that you already finished Linux. Thank you so much. When can you finish Windows build? I can't wait to announce it :D

**Comment by oguzhaninan** [comment]
Linux packaging is complete, but I found that the packages I used for this were causing problems. I will have to look at the cause of these problems. I need to prepare and test a suitable environment for Windows.

**Comment by yakuter** [comment]
Windows and MacOS is done! Let's work on linux ;)

**Comment by yakuter** [comment]
Linux is done! Thank you @oguzhaninan
