### ISSUE TITLE
Textarea instead of text input needed on private notes

### ISSUE THREAD

**Issue by yakuter** [passwall/passwall-desktop#7]
**Is your feature request related to a problem? Please describe.**
In Private Notes category, the Private Note field is text input for now and it is not useful because notes can be long as paragraphs.
<img width="389" alt="Screen Shot 2020-07-04 at 20 10 04" src="https://user-images.githubusercontent.com/3696314/86517545-7ba0cf00-be32-11ea-9f5a-065a16b085dc.png">

**Describe the solution you'd like**
We need to change this input text to textarea as in the picture.
![Screen Shot 2020-07-04 at 20 08 34](https://user-images.githubusercontent.com/3696314/86517562-95daad00-be32-11ea-9cd5-0928472b124a.png)

Does anyone want to work on this?

**Comment by bufgix** [comment]
I can handle this

**Comment by yakuter** [comment]
Great, thank you @bufgix
