### ISSUE TITLE
Close popup after click Use This

### ISSUE THREAD

**Issue by yakuter** [passwall/passwall-desktop#8]
**Describe the bug**
The **Use This**  popup should be closed after clicking the button but it is not.
<img width="382" alt="Screen Shot 2020-07-04 at 20 15 30" src="https://user-images.githubusercontent.com/3696314/86517667-64161600-be33-11ea-9fbb-37d6e9668851.png">

Can somebody close this popup after click :)

**Comment by umutbozdag** [comment]
I can take this one but when i try to install dependencies with yarn it gives me error about **electron-installer-debian** and **electron-installer-redhat** modules and it says:

> The platform "win32" is incompatible with this module.

 When i remove them i can run the project successfully. What should i do?

**Comment by oguzhaninan** [comment]
Would you try to use npm for install dependencies?

**Comment by umutbozdag** [comment]
I already did and it gives an error like this:

> npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for electron-installer-debian@3.1.0: wanted {"os":"darwin,linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin,linux
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

**Comment by yakuter** [comment]
@umutbozdag i see you already solved the problem in **src/renderer/components/GeneratePassword.vue**. If you can add yarn.lock and send PR, I would love to merge.

By the way, how did you solve your problem?

**Comment by umutbozdag** [comment]
> @umutbozdag i see you already solved the problem in **src/renderer/components/GeneratePassword.vue**. If you can add yarn.lock and send PR, I would love to merge.
> 
> By the way, how did you solve your problem?

I just removed those packages in my local.

**Comment by yakuter** [comment]
Closed with #10
